### ISSUE TITLE
mobilenetssd在dsp以及高通cpu板子，有测试过速度吗？大约多少呢？

### ISSUE THREAD

**Issue by Travis-Lee** [b1xian/mobilenet-ssd-snpe#1]

**Comment by b1xian** [comment]
具体数值记不清了，印象中dsp运行mobilenetv1-ssd量化模型几毫秒的样子。
使用经验来说，相较于使用cpu运行非量化模型，在dsp运行量化模型的推理速度会提升十倍以上。只是dsp对一些算子和网络结构的支持和优化不佳，精度损失不好控制。

**Comment by b1xian** [comment]
> _No description provided._

具体数值记不清了，印象中dsp运行mobilenetv1-ssd量化模型几毫秒的样子。
使用经验来说，相较于使用cpu运行非量化模型，在dsp运行量化模型的推理速度会提升十倍以上。只是dsp对一些算子和网络结构的支持和优化不佳，精度损失不好控制。

**Comment by Travis-Lee** [comment]
> > _No description provided._
> 
> 具体数值记不清了，印象中dsp运行mobilenetv1-ssd量化模型几毫秒的样子。
> 使用经验来说，相较于使用cpu运行非量化模型，在dsp运行量化模型的推理速度会提升十倍以上。只是dsp对一些算子和网络结构的支持和优化不佳，精度损失不好控制。

我用了你的cpu的代码在板子上跑了，你有dsp的纯c++的或者c的代码吗？

**Comment by b1xian** [comment]
> > > _No description provided._
> > 
> > 
> > 具体数值记不清了，印象中dsp运行mobilenetv1-ssd量化模型几毫秒的样子。
> > 使用经验来说，相较于使用cpu运行非量化模型，在dsp运行量化模型的推理速度会提升十倍以上。只是dsp对一些算子和网络结构的支持和优化不佳，精度损失不好控制。
> 
> 我用了你的cpu的代码在板子上跑了，你有dsp的纯c++的或者c的代码吗？

生产项目有使用，有空我加到这个demo里

**Comment by Travis-Lee** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 具体数值记不清了，印象中dsp运行mobilenetv1-ssd量化模型几毫秒的样子。
> > > 使用经验来说，相较于使用cpu运行非量化模型，在dsp运行量化模型的推理速度会提升十倍以上。只是dsp对一些算子和网络结构的支持和优化不佳，精度损失不好控制。
> > 
> > 
> > 我用了你的cpu的代码在板子上跑了，你有dsp的纯c++的或者c的代码吗？
> 
> 生产项目有使用，有空我加到这个demo里

########################################
#########################################

是否方便留个联系方式，可以共同讨论下，怎么好的使用snpe，感谢了

**Comment by b1xian** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > 具体数值记不清了，印象中dsp运行mobilenetv1-ssd量化模型几毫秒的样子。
> > > > 使用经验来说，相较于使用cpu运行非量化模型，在dsp运行量化模型的推理速度会提升十倍以上。只是dsp对一些算子和网络结构的支持和优化不佳，精度损失不好控制。
> > > 
> > > 
> > > 我用了你的cpu的代码在板子上跑了，你有dsp的纯c++的或者c的代码吗？
> > 
> > 
> > 生产项目有使用，有空我加到这个demo里
> 
> ########################################
> #########################################
> 
> 是否方便留个联系方式，可以共同讨论下，怎么好的使用snpe，感谢了

13269515093,微信
