### ISSUE TITLE
批处理速度问题

### ISSUE THREAD

**Issue by liujianisme** [b1xian/mobilenet-ssd-snpe#10]
你好，我对您的代码做了批处理输入输出修改，但是速度优化不明显，请问一下这个是怎么解决呢？

**Comment by b1xian** [comment]
通过修改snpe输入的batch size吗

**Comment by liujianisme** [comment]
我是按照官方文档给的示例代码修改的 https://developer.qualcomm.com/sites/default/files/docs/snpe/input_batch.html

**Comment by b1xian** [comment]
> 我是按照官方文档给的示例代码修改的 https://developer.qualcomm.com/sites/default/files/docs/snpe/input_batch.html

我没有测试过batch的效果，你用的是cpu runtime吗？试试gpu和dsp，snpe对cpu似乎没做什么优化效率比较低。

**Comment by liujianisme** [comment]
我用的是GPU的，dsp没试过，我用的aarch64_ubuntu1804_rb5的系统，运行环境测试的程序没找到DSP runtime

**Comment by liujianisme** [comment]
还有个问题想请教一下，请问你有试过使用snpe的userbuff做输入输出嘛？我这边模型输入和输出都需要做预处理和后处理，看官方文档说建议使用UserBuff，这方面我不是很熟悉。

**Comment by b1xian** [comment]
> 还有个问题想请教一下，请问你有试过使用snpe的userbuff做输入输出嘛？我这边模型输入和输出都需要做预处理和后处理，看官方文档说建议使用UserBuff，这方面我不是很熟悉。

我没有用过UserBuffer,抱歉呀

**Comment by liujianisme** [comment]
客气啦，非常感谢您的答复
