### ISSUE TITLE
Another question for building in linux-x86_64

### ISSUE THREAD

**Issue by JosephKKim** [b1xian/mobilenet-ssd-snpe#11]
I am trying to run this model in my ubuntu PC before porting it into a device I have.
But when I try to build program in linux-x86_64, giving TARGET_INDEX=0 to build.sh file. 

The error is as follows, 
`[100%] Linking CXX executable test-mobilenet-ssd
/usr/bin/x86_64-linux-gnu-ld: cannot find -lIlmImf
collect2: error: ld returned 1 exit status
CMakeFiles/test-mobilenet-ssd.dir/build.make:98: recipe for target 'test-mobilenet-ssd' failed
make[2]: *** [test-mobilenet-ssd] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/test-mobilenet-ssd.dir/all' failed
make[1]: *** [CMakeFiles/test-mobilenet-ssd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

from google I found that this is a linking issue, but cannot find way to solve this error. 
Can any body help? 

Thanks in advance, Joseph

**Comment by b1xian** [comment]
there is no libIlmImf.a in third_party/opencv_2.4.13.4/linux-x86_64/3rdparty, compile OpenCV to generate it.

**Comment by JosephKKim** [comment]
sorry for the dumb question but can you give some example codes compiling cv2? 
Now I'm just using build.sh..

**Comment by b1xian** [comment]
> sorry for the dumb question but can you give some example codes compiling cv2? Now I'm just using build.sh..

I've already fixed the library issue with the latest commit.
[build opencv on ubuntu](https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html)

**Comment by JosephKKim** [comment]
Thank you so much for the quick response.. 
but when I try to use test-mobilenet-ssd 
after build, by using command `./test-mobilenet-ssd`
this error comes out `./test-mobilenet-ssd: error while loading shared libraries: libopencv_imgproc.so.2.4: cannot open shared object file: No such file or directory`

I've changed few lines in run.example.sh since I thought that there's no need of adb push command.

So my test_snpe-demo directory in local PC has all the files such as 1.jpg, 1.raw .... libomp.so .. and so on and also execution file. I cannot find what's missing can you help me one more time?? 

once again thanks for the help.

**Comment by b1xian** [comment]
> Thank you so much for the quick response.. but when I try to use test-mobilenet-ssd after build, by using command `./test-mobilenet-ssd` this error comes out `./test-mobilenet-ssd: error while loading shared libraries: libopencv_imgproc.so.2.4: cannot open shared object file: No such file or directory`
> 
> I've changed few lines in run.example.sh since I thought that there's no need of adb push command.
> 
> So my test_snpe-demo directory in local PC has all the files such as 1.jpg, 1.raw .... libomp.so .. and so on and also execution file. I cannot find what's missing can you help me one more time??
> 
> once again thanks for the help.

try the latest commit.

**Comment by JosephKKim** [comment]
Thank you so much @b1xian!!!
I can thank you enough for making this repository work in my linux environment.

Hope I get better understanding in cross compiling and using cv tool in c++ environment like you. 
Once, again thank you for the quick response, hope you have a good day.


Joseph

You may close this issue!

**Comment by b1xian** [comment]
> Thank you so much @b1xian!!! I can thank you enough for making this repository work in my linux environment.
> 
> Hope I get better understanding in cross compiling and using cv tool in c++ environment like you. Once, again thank you for the quick response, hope you have a good day.
> 
> Joseph
> 
> You may close this issue!

I'm glad to help you.
