### ISSUE TITLE
--use_dsp  not speed up

### ISSUE THREAD

**Issue by mathpopo** [b1xian/mobilenet-ssd-snpe#4]
adb shell "cd ${bin_path} \
       && export LD_LIBRARY_PATH=${bin_path}:${LD_LIBRARY_PATH} \
       && ./test-mobilenet-ssd 2 mobilenet_iter_73000_int8.dlc 1.jpg"

(base) chenxin@Nitro-AN515:~/Downloads/mobilenet-ssd-snpe$ ./run_example.sh
build/android-arm64-v8a/test_snpe_demo.... 18.7 MB/s (50124830 bytes in 2.560s)
into main.
infer_type:2
model_name:mobilenet_iter_73000_int8.dlc
img_path path:1.jpg
SNPE model init, using runtime dsp_fixed8_tf
init success...
engine inference success...
**model_cost:22.033428019**
/data/local/tmp/test_snpe_demo/result....led. 13.9 MB/s (48670 bytes in 0.003s)

adb shell "cd ${bin_path} \
       && export LD_LIBRARY_PATH=${bin_path}:${LD_LIBRARY_PATH} \
       && ./test-mobilenet-ssd 2 mobilenet_iter_73000_int8.dlc 1.jpg --use_dsp"

(base) chenxin@Nitro-AN515:~/Downloads/mobilenet-ssd-snpe$ ./run_example.sh
build/android-arm64-v8a/test_snpe_demo.... 19.0 MB/s (50124830 bytes in 2.516s)
into main.
infer_type:2
model_name:mobilenet_iter_73000_int8.dlc
img_path path:1.jpg
SNPE model init, using runtime dsp_fixed8_tf
init success...
engine inference success...
**model_cost:21.414628019**
/data/local/tmp/test_snpe_demo/result....led. 12.8 MB/s (48670 bytes in 0.004s)

**Comment by mathpopo** [comment]
using runtime dsp_fixed8_tf
 难道就是默认的dsp？

**Comment by b1xian** [comment]
demo的第一个输入参数为runtime选择：0-cpu 1-gpu 2-dsp。
第二个输入参数为模型地址，默认push了mobilenet_iter_73000.dlc和mobilenet_iter_73000_int8.dlc两个模型，分别为fp32和int8模型。
使用cpu推理: ./test-mobilenet-ssd 0 mobilenet_iter_73000.dlc 1.jpg

**Comment by mathpopo** [comment]
./test-mobilenet-ssd 0 mobilenet_iter_73000.dlc 1.jpg
model_cost:568.99428019

./test-mobilenet-ssd 1 mobilenet_iter_73000.dlc 1.jpg
SNPE model init, using runtime gpu_float32_16_hybrid
build engine error : error_code=1000; error_message=Layer is not supported. error_code=1000; error_message=Layer is not supported. Layer detection_out of type SsdDetectionOutput not supported by GPU runtime; error_component=Model Validation; line_no=361; thread_id=534258504944; error_component=Model Validation; line_no=264; thread_id=534328953264
Segmentation fault

./test-mobilenet-ssd 2 mobilenet_iter_73000.dlc 1.jpg
model_cost:29.783928019


./test-mobilenet-ssd 0 mobilenet_iter_73000_int8.dlc 1.jpg
SNPE model init, using runtime cpu_float32
model_cost:430.28128019

./test-mobilenet-ssd 2 mobilenet_iter_73000_int8.dlc 1.jpg
model_cost:23.094228019


我有个疑问哈：
//runtime_t = zdl::DlSystem::Runtime_t::GPU_FLOAT32_16_HYBRID;
        runtime_t = zdl::DlSystem::Runtime_t::GPU;

但是依然是：SNPE model init, using runtime gpu_float32_16_hybrid

**Comment by mathpopo** [comment]
file:///home/chenxin/Downloads/snpe-1.43.0.2307/doc/html/cplus_plus_tutorial.html
zdl::DlSystem::Runtime_t checkRuntime()
{
    static zdl::DlSystem::Version_t Version = zdl::SNPE::SNPEFactory::getLibraryVersion();
    static zdl::DlSystem::Runtime_t Runtime;
    std::cout << "SNPE Version: " << Version.asString().c_str() << std::endl; //Print Version number
    if (zdl::SNPE::SNPEFactory::isRuntimeAvailable(zdl::DlSystem::Runtime_t::GPU)) {
        Runtime = **zdl::DlSystem::Runtime_t::GPU**;
    } else {
        Runtime = zdl::DlSystem::Runtime_t::CPU;
    }
    return Runtime;
}

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/Downloads/mobilenet-ssd-snpe$ git diff run_example.sh
diff --git a/run_example.sh b/run_example.sh
index aac5bba..d921641 100755
--- a/run_example.sh
+++ b/run_example.sh
@@ -75,6 +75,6 @@ adb shell "chmod +x ${bin_path}/test-mobilenet-ssd"
 #       && ./test-mobilenet-ssd mobilenet_iter_73000_int8.dlc 1.raw"
 adb shell "cd ${bin_path} \
        && export LD_LIBRARY_PATH=${bin_path}:${LD_LIBRARY_PATH} \
-       && ./test-mobilenet-ssd 2 mobilenet_iter_73000_int8.dlc 1.jpg"
+       && ./test-mobilenet-ssd 1 mobilenet_iter_73000_int8.dlc 1.jpg"
 
 adb pull $bin_path"result.jpg" ./
(base) chenxin@Nitro-AN515:~/Downloads/mobilenet-ssd-snpe$ git diff src/snpe_engine.cpp
diff --git a/src/snpe_engine.cpp b/src/snpe_engine.cpp
index f511671..c157aad 100644
--- a/src/snpe_engine.cpp
+++ b/src/snpe_engine.cpp
@@ -48,7 +48,7 @@ int SnpeEngine::setRuntime(std::string infer_type){
     zdl::DlSystem::Runtime_t runtime_t;
 
     if (infer_type == "1") {
-        runtime_t = zdl::DlSystem::Runtime_t::GPU_FLOAT32_16_HYBRID;
+        runtime_t = zdl::DlSystem::Runtime_t::GPU;//_FLOAT32_16_HYBRID;
     } else if (infer_type == "2") {
         runtime_t = zdl::DlSystem::Runtime_t::DSP;
     } else {

**Comment by mathpopo** [comment]
Enumerator
--
CPU_FLOAT32 | Run the processing on Snapdragon CPU. Data: float 32bit Math: float 32bit
GPU_FLOAT32_16_HYBRID | Run the processing on the Adreno GPU. Data: float 16bit Math: float 32bit
DSP_FIXED8_TF | Run  the processing on the Hexagon DSP. Data: 8bit fixed point Tensorflow  style format Math: 8bit fixed point Tensorflow style format
GPU_FLOAT16 | Run the processing on the Adreno GPU. Data: float 16bit Math: float 16bit
AIP_FIXED8_TF | Run  the processing on Snapdragon AIX+HVX. Data: 8bit fixed point Tensorflow  style format Math: 8bit fixed point Tensorflow style format
CPU | Default legacy enum to retain backward compatibility. CPU = CPU_FLOAT32
GPU | Default legacy enum to retain backward compatibility. GPU = GPU_FLOAT32_16_HYBRID
DSP | Default legacy enum to retain backward compatibility. DSP = DSP_FIXED8_TF
UNSET | Special value indicating the property is unset.

**Comment by mathpopo** [comment]
我明白了

**Comment by b1xian** [comment]
> 我明白了

👌
