### ISSUE TITLE
how to use android folder?

### ISSUE THREAD

**Issue by mathpopo** [b1xian/mobilenet-ssd-snpe#5]

**Comment by b1xian** [comment]
使用android studio导入android目录即可

**Comment by mathpopo** [comment]
ndk.dir=/home/chenxin/armnn-devenv/toolchains/android-ndk-r17b
build结束后，然后  “run（app）”也没啥反应

**Comment by mathpopo** [comment]
More than one file was found with OS independent path 'lib/arm64-v8a/libSNPE.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

**Comment by mathpopo** [comment]
SET(snpe_lib_dir ${CMAKE_SOURCE_DIR}/src/main/jni-libs/${ANDROID_ABI}/libSNPE.so)这不是写死了吗？

**Comment by b1xian** [comment]
> More than one file was found with OS independent path 'lib/arm64-v8a/libSNPE.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
你用的是什么设备呢？
可以检查一下apk的安装路径下lib/arm64中的so文件是否正确

**Comment by b1xian** [comment]
> SET(snpe_lib_dir ${CMAKE_SOURCE_DIR}/src/main/jni-libs/${ANDROID_ABI}/libSNPE.so)这不是写死了吗？

cmake是build jni的so时使用的，应该和你这里的报错无关

**Comment by mathpopo** [comment]
你用的是什么设备呢？就是安卓手机啊，
apk的安装路径下lib/arm64中的so文件是否正确---  > 手机？比如什么路径？

**Comment by mathpopo** [comment]
是在build阶段发生的，不应该牵扯到手机吧？

lib/armeabi-v7a/libSNPE.so   不应该是jni_lib吗？

**Comment by b1xian** [comment]
> 是在build阶段发生的，不应该牵扯到手机吧？
> 
> lib/armeabi-v7a/libSNPE.so 不应该是jni_lib吗？

哦哦，是build阶段的错误，我这边不会报libSNPE.so重复的错误，你更新一下代码再试一下

**Comment by b1xian** [comment]
> 是在build阶段发生的，不应该牵扯到手机吧？
> 
> lib/armeabi-v7a/libSNPE.so 不应该是jni_lib吗？

问题解决了吗

**Comment by mathpopo** [comment]
@b1xian 我需要重新下载一下代码吗？

**Comment by b1xian** [comment]
> @b1xian 我需要重新下载一下代码吗？

嗯重新下载一下吧
