### ISSUE TITLE
Have question about using cv2 with snpe

### ISSUE THREAD

**Issue by JosephKKim** [b1xian/mobilenet-ssd-snpe#9]
This actually is not an issue about the code but personal question as a newbie in SNPE  and computer vision.
I am currently working on project that uses human pose estimation network and inference the results in Qualcomm 8155AP.

I was inspired by your code and want to use cv2 in my code as well. Problem is that there are so many dependencies and I don't know which ones are essential for building a program. 

Can you please give me a guide for making program with SNPE and CV2?
It is so difficult to get information and the official SNPE tutorial and example codes are all I have. 
Thanks,
Joseph

**Comment by liujianisme** [comment]
Crosscompile opencv on host pc then upload to chip, then you can use opencv

**Comment by JosephKKim** [comment]
@JimmyLauren Thanks for the information I'm not used to using deep learning models in chips 
Crosscompile would be a good keyword for starting googling THX

**Comment by JosephKKim** [comment]
@JimmyLauren Can you help me with another issue? 
#11 
Thanks for the help Jimmy.
